package schurmanb.comp4004.a1.src;

public class Item implements Comparable<Item>
{
	Integer iID;	// item ID generated by library database
	Title title; 	// referencing Title object
	
	public Item( int iID, Title title ){
		this.iID = iID;
		this.title = title;
	}
	
	public Integer getItemID(){
		return this.iID;
	}
	
	public Title getReferencingTitle(){
		return this.title;
	}
	
	@Override 
	public String toString(){
		return title + ". ItemID#"+iID;
	}
	
	@Override 
	public int compareTo( Item other ){
		return this.getItemID().compareTo(other.getItemID());
	}
}
